### ISSUE TITLE
Login issues with additional age confirmation page

### ISSUE THREAD

**Issue by Optophonic** [Ingo-FP-Angel/plugin.video.filmfriend.de#10]
I try to set-up the software for my kids and during the login procedure the plug-in stops with an unknown error. 

During the (web) login procedure there is an additional screen which asks to confirm the data transfer of the age. I suspect this could be the issue:

![Screenshot_20240104_100144](https://github.com/Ingo-FP-Angel/plugin.video.filmfriend.de/assets/11292871/a5e7e551-8a0b-460d-85df-ef288b1cb68b)

**Comment by Ingo-FP-Angel** [comment]
Which library is that?

If it's VÖBB (Berlin) by any chance, there's already an issue #4

**Comment by Optophonic** [comment]
No, it's not Berlin. It's the public library in Nürnberg, https://www.nuernberg.de/internet/stadtbibliothek/

**Comment by Ingo-FP-Angel** [comment]
When I select "Stadtbibliothek im Bildungscampus Nürnberg" on https://www.filmfriend.de I first get to a page where I can choose between "Anmelden (Login via IP)" and "Login mit Bibliotheksausweis".

Which one is that?

**Comment by Optophonic** [comment]
You need to choose the second one "Login with Bibliotheksausweis"

**Comment by Ingo-FP-Angel** [comment]
Oh, and would you expect the plugin to only show/play movies/episodes that match the "Altersfreigabe"?
How does the Filmfriend Web UI behave for non-Adults?

**Comment by Optophonic** [comment]
After the login procedure and the age confirmation Filmfriend just doesn't show films which are not appropriate. This is fully transparent from a users perspective. I wouldn't expect that any further changes are necessary for navigation.

**Comment by Ingo-FP-Angel** [comment]
The thing is, I need someone to analyze the technical details as I don't have username/password for libraries of other cities.

**Comment by Ingo-FP-Angel** [comment]
Would you be able to test a work-in-progress version of the addon?
Available at https://github.com/Ingo-FP-Angel/plugin.video.filmfriend.de/releases/tag/1.0.8-beta.3

I've done some first implementation based on feedback of someone using VÖBB (Berlin), but the code I wrote should be generic and hopefully work for all/at least some more libraries with an age confirmation page.

I suspect it might not work and if so, could you PM me the debug log at https://www.kodinerds.net (I'm using the same username there, too)?

**Comment by Optophonic** [comment]
I just tested the latest version and it works perfectly fine. Thanks for your efforts!
